montonio:
    #    secret-key: {type here secret-key which used to montonio payment gateway}
    #    access-key: {type here acess-key which used to montonio payment gateway}
    payment-url: https://sandbox-payments.montonio.com?payment_token=
    bank-list: https://api.payments.montonio.com/pis/v2/merchants/aspsps
    payment-details: https://api.payments.montonio.com/pis/v2/merchants/payments

server:
    port: 8080

header:
    key: Authorization